""" C++ code generator
From YAML descriptor, generate .h file(s) containing user data structures
and the .cpp file that implements the initialization of the metadata
describing the contents of those structures.

Usage: python yaml_code_gen.py [source YAML file]

"""

import yaml
import sys
import time
import datetime

indent = "    "

def getCommonHdr(script, inputFile):
    return ("// Don't modify this file.  It was generated by " + script +
            "\n// from " + inputFile + " on " + str(datetime.date.today()) + ".\n")

def getDeclHeader(script, inputFile):
    return (getCommonHdr(script, inputFile) +
            "// It contains data structure definitions for configurable items managed by cfg_man.\n\n")
    
def getInitHeader(script, inputFile):
    return (getCommonHdr(script, inputFile) +
            "// It contains initialization of metadata for configurable items managed by cfg_man.\n\n")

    
class Id_generator():
    "Generate ID for TLV: the data struct of existing IDs in the context is used to avoid allocating an IDs that is taken"
    def __init__(self, id_dlist):

        self.id = 0
        self.id_dict = id_dlist
        
        # xxx debug code
        if id_dlist is not None:
	        for d in id_dlist:
	            print d
        
        
    def get_id(self):
        "Generate an ID, but not one that's already in use in the context"
        if self.id_dict is None:
            id_string = str(self.id)
            self.id += 1
            return id_string
        else:
            print "The data struct where we should find", component_name, "is", self.id_dict
            #id = get_value_from_dictionary_list(self.id_dict, component_name)
            #print "and the ID we got therefrom is" , id
            


class Item:
    def __init__(self, d, container_id_gen, old_id):
        self.d = d
        if old_id is not None:
            print d['name'], "has old ID", old_id['id']
            self.id = str(old_id['id'])
        else:
            print d['name'], "has no old ID"
            self.id = container_id_gen.get_id()
        
    def get_definition(self):
        "Definitions of structs definitions for composites"
        return self.get_struct_definition()
        
    def get_metadata_name(self):
        return self.d['name'] + "_data"
        
    def get_common_metadata_init(self):
        "Return string representing initialization of the common metadata structure"
        s = indent + "{\n"
        s += 2 * indent + "\"" + self.d['name'] + "\",\n"
        s += 2 * indent + self.id + ",\n" # xxx fix this: IDs should be constant as possible within composites
        s += 2 * indent + self.get_size() + ",\n"
        s += 2 * indent
        if self.d['persistent']:
             s += "true\n"
        else:
            s += "false\n"
        s += indent + "},\n"
        return s
        
    
class SimpleItem(Item):
    def __init__(self, d, container_id_gen, old_id):
        Item.__init__(self, d, container_id_gen, old_id)
        self.is_string_type = False # By default, items aren't strings
        if "string" in d['type']:
            self.is_string_type = True
            self.string_len = d['type'].split()[1]
                   
    def verify(self):
        "Check item description in YAML file is valid and consistent."
        # Not much to check here -- if the basics like 'name' and 'type' are absent, an exception is raised,
        # maybe even before we get to this point.        
        return True
        
    def get_ids(self):
        "Get xxx"
        return {self.d['name']: {'id': int(self.id)}}
            
    def get_init(self):
        "Return string containing initialization of the metadata"
        s = self.get_metadata_init()
        s += "const cm_simple_descriptor " + self.d['name'] + "(&" + self.get_metadata_name() + ");\n"
        return s
        
    def get_metadata_init(self):
        s = "const cm_simple_metadata " + self.get_metadata_name() + " = \n{\n"
        s += self.get_common_metadata_init()
        
        s += indent
        if 'set' in self.d:
            s += self.d['set']
        else:
            s += "NULL"
        s += ",\n"
        
        s += indent
        if 'setdef' in self.d:
            s += self.d['setdef']
        else:
            s += "NULL"
        s += ",\n"
        
        s += indent
        if 'print' in self.d:
            s += self.d['print']
        else:
            s += "NULL"
        s += ",\n"
        
        s += "};\n"
        return s
    
    def get_type_and_name(self, aggrType):
        "Get the type and the name, part of the definition line"
        if self.is_string_type:
            s = "char "
        else:
            s = self.d['type'] + " "
        if aggrType == 'owned':
            s += "* "
        s += self.d['name']
        if self.is_string_type:
            s += "[" + self.string_len + "]"
        return s
        
    def get_size(self):
        s = "sizeof("
        if self.is_string_type:
            s += "char) * " + self.string_len
        else:
            s += self.d['type'] + ")"
        return s
        
    def get_definition(self):
        """No struct def for simple"""
        return ""
        
        
def get_value_from_dictionary_list(dlist, key):
    "Helper function: from input list of dictionaries, return the value of dictionary with the desired key (or None)"
    for d in dlist:
        if key in d:
            return d[key]

      
class CompositeItem(Item):
    def __init__(self, d, container_id_gen, old_id):
        Item.__init__(self, d, container_id_gen, old_id)
        self.id_gen = Id_generator(old_id)
        # xxx debug code
        if old_id is not None:
            print "Items in ID dictionary for", d['name']
            print old_id['items']
            print
        self.aggregates = []
        for a in self.d['aggregate']:
            component_id = None
            if old_id is not None:
                component_id = get_value_from_dictionary_list(old_id['items'], a['item']['name'])
            self.aggregates.append(makeAggregate(a, self.id_gen, component_id))

    def verify(self):
        "Check item description in YAML file is valid and consistent."
        for aggr in self.aggregates:
            aggr.verify()
        return True
        
    def get_ids(self):
        "Generate dictionary of IDs, showing IDs assigned in the object hierarchy"
        items = []
        id_dict = {self.d['name']: {'id': int(self.id), 'items': items}}
        for aggr in self.aggregates:
            items.append(aggr.item.get_ids())
        return id_dict
            
    def get_definition(self):
        "Return string representing struct definition, including pre-pended definitions of referenced structs"
        s = ""
        for aggr in self.aggregates:
            s += aggr.get_constant_definition()
            s += aggr.item.get_definition()
        s += "\nstruct " + self.get_type() + "\n{\n"
        for aggr in self.aggregates:
            s += indent + aggr.get_instance_definition()
        s += "};\n"
        return s
        
    def get_init(self):
        "Return string containing initialization of the metadata, including pre-pended initialization of included data"
        s = ""
        for aggr in self.aggregates:
            s += aggr.get_init(self.get_type(), self.id_gen) 
        s += self.get_aggr_list_init()
        s += self.get_metadata_init()
        s += "const cm_composite_descriptor " + self.d['name'] + "(&" + self.get_metadata_name() + ");\n"
        return s
        
    def get_aggr_list_init(self):
        s = "const cm_aggregate * const " + self.get_aggr_list_name() + "[] = \n{\n"
        for a in self.d['aggregate']:
            s += indent + "&" + a['item']['name'] + "_aggr,\n"
        s += "\n};\n"
        return s
        
    def get_metadata_init(self):
        s = "const cm_composite_metadata " + self.get_metadata_name() + " = \n{\n"
        s += self.get_common_metadata_init()
        s += indent + self.get_aggr_list_name() + ",\n"
        s += indent + "sizeof(" + self.get_aggr_list_name() + ")/sizeof(" + self.get_aggr_list_name() + "[0])\n"
        s += "};\n"
        return s
        
    def get_aggr_list_name(self):
        return self.d['name'] + "_aggr_list"
        
    def get_type(self):
        return "t_" + self.d['name']
        
    def get_type_and_name(self, aggrType):
        s = self.get_type() + " "
        if aggrType == 'owned':
            s += "* "
        s += self.d['name']
        return s
        
    def get_size(self):
        return "sizeof(" + self.get_type() + ")"
              
                    
class Aggregate:
    def __init__(self, d, id_gen, old_id):
        self.d = d
        self.item = makeItem(self.d['item'], id_gen, old_id)
        
    def verify(self):
        "Check description in YAML file is valid and consistent."
        return self.item.verify()       
        
    def get_init(self, container_type_name, id_gen):
        "Return initialization string"
        s = self.item.get_init()
        s += "const cm_aggregate_data " + self.get_data_name() + " = {&"
        s += self.item.d['name'] + ", " + self.get_count_str()
        s += ", offsetof(" + container_type_name + ", " + self.item.d['name'] + ")};\n"
        s += self.get_instantiate()
        
        return s
        
    def get_data_name(self):
        return self.d['item']['name'] + "_aggr_data"
        
    def get_count_str(self):
        "Return a string representing the count: either the name of a symbolic constant, or just a string of an integer."
        try:
            count = self.d['count']['name']
        except:
            count = str(self.d['count'])
        return count
        
    def get_constant_definition(self):
        "Return string representing the symbolic constants used in the aggregate count"
        s = ""
        try:
            constant = self.d['count']
            s += "const " + constant['type'] + " " + constant['name'] + " = " + str(constant['value']) + ";\n"
        except:
            # If no counter that includes type, name and value, then there are no constants
            pass
        return s
        
class ContainedAggregate(Aggregate):
    def __init__(self, d, id_gen, old_id):
        Aggregate.__init__(self, d, id_gen, old_id)
        
    def get_instance_definition(self):
        s = self.item.get_type_and_name('contained')
        if self.d['count'] != 1:
            s += "[" + self.get_count_str() + "]"
        return s + ";\n"
        
    def get_type(self):
        return "cm_contained_aggregate"
        
    def get_instantiate(self):
        s = "const " + self.get_type() + " " + self.item.d['name'] + "_aggr(&" + self.get_data_name() + ");\n\n"
        return s
        
        
class OwnedAggregate(Aggregate):
    def __init__(self, d, id_gen, old_id):        
        Aggregate.__init__(self, d, id_gen, old_id)
        
    def verify(self):
        "Check description in YAML file is valid and consistent."
        self.verify_counter()
        self.item.verify()
        
    def verify_counter(self):
        "An owned aggregate that can contain more than one instance needs a counter"
        if not 'counter' in self.d:
            max_count = self.get_max_count()
            if max_count > 1:
                print "Warning: aggregate for", self.d['item']['name'], "has no counter, but max_count is", max_count
                return False
        return True  
        
    def get_instance_definition(self):
        return self.item.get_type_and_name('owned') + ";\n"
        
    def get_type(self):
        return "cm_owned_aggregate"
        
    def get_instantiate(self):
        s = "const " + self.get_type() + " " + self.item.d['name'] + "_aggr(&" + self.get_data_name()
        if 'counter' in self.d:
            s += ", &" + self.d['counter']['item']['name'] + "_aggr"
        else:
            s += ", NULL"
        s += ");\n\n"
        return s
        
    def get_max_count(self):
        "Return numerical value for maximum number of instances of owned aggregate"
        try:
            # The value of the symbolic constant
            return self.d['count']['value']
        except:
            # Simple case: return the value
            return self.d['count']
        
        
def makeItem(d, container_id_gen, old_id):
    "Factory method returns an Item object of the requested class"
    if 'aggregate' in d: 
        return CompositeItem(d, container_id_gen, old_id)
    else:
        return SimpleItem(d, container_id_gen, old_id)
        

def makeAggregate(d, id_gen, old_id):
    "Factory method returns an Aggregate object of the requested class"
    if d['type'] == 'owned': 
        return OwnedAggregate(d, id_gen, old_id)
    else:
        return ContainedAggregate(d, id_gen, old_id)

        
def loadCfgData(cfgFileName):
    "Load configuration metadata from YAML config file"
    try:
        f = open(cfgFileName)
    except:
        print "Configuration file name not given."
        return
        
    print "Reading config file", cfgFileName
    try:
        data = yaml.load(f)
    except:
        print cfgFileName, "is not a YAML file"
    
    f.close()
    
    try:
        return data['item']
    except:
        print "Root element in", cfgFileName, "is not an item."

def loadIdData():
    "Load ID data and return version and dictionary, or None if there's a problem with the input file"
    fname = "cfg_id.yaml"
    v = None
    data = None

    try:
        fid_old = open(fname)
        d = yaml.load(fid_old)
        v = d['version']
        data = d['data']
    
    except IOError:
        print "Can't open", fname
    except KeyError:
        print fname, "is missing mandatory keys"
    except:
        print fname, "is not a valid YAML file"
    return v, data


def saveIdData(version, old_id):
    "If there has been a change in ID data, save it with a new version number."
    d = {}
    d['data'] = baseItem.get_ids()
    if d['data'] == old_id:
        return
        
    if version is None:
        d['version'] = 0
    else:
        d['version'] = version + 1
    print "saveIdData: changed, version", d['version']
    fid_new = open("cfg_id.yaml", "w")
    fid_new.write(yaml.dump(d, default_flow_style=False))
        

base_item_config = loadCfgData(sys.argv[1])
if base_item_config is None:
    sys.exit()
    
version, id_dict = loadIdData()

try:
    base_id_dict = id_dict[base_item_config['name']]
except:
    # The ID data file has no ID corresponding to the base item's name
    print "No", base_item_config['name'], "in ID data file: generate new IDs"
    base_id_dict = None

baseItem = makeItem(base_item_config, Id_generator(None), base_id_dict)
baseItem.verify()
finit = open("cfg.cpp", "w")
fdecl = open("cfg.h", "w")
fdecl.write(getDeclHeader(sys.argv[0], sys.argv[1]))
finit.write(getInitHeader(sys.argv[0], sys.argv[1]))
fdecl.write(baseItem.get_definition())
finit.write(baseItem.get_init())
finit.close()
fdecl.close()
saveIdData(version, id_dict)
