""" C++ code generator
From YAML descriptor, generate .h file(s) containing user data structures
and the .cpp file that implements the initialization of the metadata
describing the contents of those structures.

Usage: python yaml_code_gen.py [source YAML file]

todo:
Should we mark items in the ID file that are no longer present in the config file?
We retain the IDs in the ID file (so this script can avoid re-using them), but
it could be useful to see what's no longer used in the current config without
having to compare the config file and the ID file.

"""

import yaml
import sys
import datetime
import os
import collections

indent = "    "

def getCommonHdr(script, inputFile):
    return ("// Don't modify this file.  It was generated by " + script +
            "\n// from " + inputFile + " on " + str(datetime.date.today()) + ".\n")

def getDeclHeader(script, inputFile):
    return (getCommonHdr(script, inputFile) +
            "// It contains data structure definitions for configurable items managed by cfg_mgr.\n\n")
    
def getInitHeader(script, inputFile):
    return (getCommonHdr(script, inputFile) +
            "// It contains initialization of metadata for configurable items managed by cfg_mgr.\n\n")

def getIdHeader(script):
    return ("# This file is both input to and output from " + script + ".\n" +
	        "# It 'remembers' the ID that's used to identify each item in NVRAM, for interoperability\n" +
			"# between different versions of the user-defined configurable item hierarchy.\n" +
	        "# It may be modified, typically to remove an item whose ID may be re-allocated because it\n" +
            "# is no longer used anywhere.\n")
    
class Id_generator():
    "Generate IDs for TLV: the data struct of existing IDs in the context is used to avoid allocating IDs that are taken"
    def __init__(self, id_dlist):
        "id_dlist is a data structure that contains IDs that are already allocated, i.e. not available"
        self.__make_id_dict(id_dlist)
        
    def get_id(self, name):
        "Generate an int ID for a name, but not one that's already in use in the context"
        id = 0
        while id in self.allocated_id.values():
            # This int is already allocated, so go to next one
            id = id + 1
        self.allocated_id[name] = id
        return str(id)
        
    def get_ids(self):
        "Get the dictionary of name:ID in use, newly-generated or not"
        return self.allocated_id
            
    def __make_id_dict(self, id_dlist):
        "From more complex data struct passed to constructor, generate a name:ID dictionary"
        self.allocated_id = collections.OrderedDict()
        if id_dlist is not None:
            for id in id_dlist:
                # Each element in ids is a dictionary with keys 'name' and 'id'
                self.allocated_id[id['name']] = id['id']
        #print "Start w", self.allocated_id


class Item:
    def __init__(self, d, container_id_gen, old_id, full_name):
        self.d = d
        self.full_name = full_name
        if old_id is not None:
            #print d['name'], "has old ID", old_id['id']
            self.id = str(old_id['id'])
        else:
            self.id = container_id_gen.get_id(d['name'])
            print d['name'], "assigned new ID", self.id
        
    def get_metadata_name(self):
        return self.full_name + "_data"
        
    def get_common_metadata_init(self):
        "Return string representing initialization of the common metadata structure"
        s = indent + "{\n"
        s += 2 * indent + "\"" + self.d['name'] + "\", // name\n"
        s += 2 * indent + self.id + ", // id\n"
        s += 2 * indent + self.get_size() + ", // size\n"
        s += 2 * indent
        if self.d['persistent']:
             s += "true\n"
        else:
            s += "false\n"
        s += indent + "},\n"
        return s
        
    def get_component_ids(self):
        "Implemented by CompositeItem"
        pass
        
    def get_access_fn(self):
        "Return string representing a fn to access the item."
        s = "const cfg_mgr::Descriptor * get_base_descriptor()\n"
        s += "{\n"
        s += indent + "return &" + self.full_name + ";\n"
        s += "}\n"
        return s
        
    
class SimpleItem(Item):
    def __init__(self, d, container_id_gen, old_id, full_name):
        Item.__init__(self, d, container_id_gen, old_id, full_name)
        self.is_string_type = False # By default, items aren't strings
        if "string" in d['type']:
            self.is_string_type = True
            self.string_len = d['type'].split()[1]
                   
    def verify(self):
        "Check item description in YAML file is valid and consistent."
        # Not much to check here -- if the basics like 'name' and 'type' are absent, an exception is raised,
        # maybe even before we get to this point.        
        return True
                    
    def get_init(self):
        "Return string containing initialization of the metadata"
        s = self.get_metadata_init()
        s += "const cfg_mgr::Simple_descriptor " + self.full_name + "(&" + self.get_metadata_name() + ");\n"
        return s
        
    def get_metadata_init(self):
        s = "const cfg_mgr::Simple_metadata " + self.get_metadata_name() + " =\n{\n"
        s += self.get_common_metadata_init()
        s += indent
        if 'set' in self.d:
            s += self.d['set']
        else:
            s += "NULL"
        s += ", // set\n"
        s += indent
        if 'setdef' in self.d:
            s += self.d['setdef']
        else:
            s += "NULL"
        s += ", // setdef\n"
        s += indent
        if 'print' in self.d:
            s += self.d['print']
        else:
            s += "NULL"
        s += ", // print\n};\n"
        return s
    
    def get_type_and_name(self, aggrType):
        "Get the type and the name, part of the definition line"
        if self.is_string_type:
            s = "char "
        else:
            s = self.d['type'] + " "
        if aggrType == 'owned':
            s += "* "
        s += self.d['name']
        if self.is_string_type:
            s += "[" + self.string_len + "]"
        return s
        
    def get_size(self):
        s = "sizeof("
        if self.is_string_type:
            s += "char) * " + self.string_len
        else:
            s += self.d['type'] + ")"
        return s
        
    def get_definition(self):
        "No struct def for simple"
        return ""
        
        
def get_value_from_dictionary_list(dlist, key):
    "Helper function: from list of dictionaries, return the value of 1st dictionary with the desired 'name' entry(or None)"
    for d in dlist:
        if d['name'] == key:
            return d

      
class CompositeItem(Item):
    def __init__(self, d, container_id_gen, old_id, full_name):
        "prefix_string, from containing item, is prefixed to this item's name to give this item's structure name"
        Item.__init__(self, d, container_id_gen, old_id, full_name)
        if old_id is not None:
            self.id_gen = Id_generator(old_id['components'])
        else:
            self.id_gen = Id_generator(None)
        self.aggregates = []
        for a in self.d['aggregate']:
            component_id = None
            if old_id is not None:
                component_id = get_value_from_dictionary_list(old_id['components'], a['item']['name'])
            self.aggregates.append(makeAggregate(a, self.id_gen, component_id, full_name))

    def verify(self):
        "Check item description in YAML file is valid and consistent."
        for aggr in self.aggregates:
            aggr.verify()
        return True
        
    def get_component_ids(self):
        "Get list of component IDs in format used to generate the ID yaml file"
        component_ids = self.id_gen.get_ids() # This dictionary includes old IDs from ID file
        components = []
        for name in component_ids:
            # An item in the complete dictionary of IDs from ID generator
            d = {} # Dictionary of dictionaries: ID, and optionally 'items', a list of item dictionaries
            d['name'] = name
            d['id'] = component_ids[name]        
            try:
                component = [a.item for a in self.aggregates if a.item.d['name'] == name][0]
                id_list = component.get_component_ids()
                if id_list is not None:
                    # The component is itself composite, so insert its entry
                    d['components'] = id_list
            except:
                # Can't find a component item with a matching name -- no longer supported
                print "%s, ID %d, is no longer in use" % (name, component_ids[name])
            components.append(d)
        return components

    def get_definition(self):
        "Return string representing struct definition, including pre-pended definitions of referenced structs"
        s = ""
        for aggr in self.aggregates:
            s += aggr.get_constant_definition()
            s += aggr.item.get_definition()
        s += "\nstruct " + self.get_type() + "\n{\n"
        for aggr in self.aggregates:
            s += indent + aggr.get_instance_definition()
        s += "};\n"
        return s
        
    def get_init(self):
        "Return string containing initialization of the metadata, including pre-pended initialization of included data"
        s = ""
        for aggr in self.aggregates:
            s += aggr.get_init(self.get_type(), self.id_gen) 
        s += self.get_aggr_list_init()
        s += self.get_metadata_init()
        s += "const cfg_mgr::Composite_descriptor " + self.full_name + "(&" + self.get_metadata_name() + ");\n"
        return s
        
    def get_aggr_list_init(self):
        s = "const cfg_mgr::Aggregate * const " + self.get_aggr_list_name() + "[] =\n{\n"
        for a in self.aggregates:
            s += indent + "&" + a.full_name + "_aggr,\n"
        s += "\n};\n"
        return s
        
    def get_metadata_init(self):
        s = "const cfg_mgr::Composite_metadata " + self.get_metadata_name() + " =\n{\n"
        s += self.get_common_metadata_init()
        s += indent + self.get_aggr_list_name() + ",\n"
        s += indent + "sizeof(" + self.get_aggr_list_name() + ")/sizeof(" + self.get_aggr_list_name() + "[0])\n"
        s += "};\n"
        return s
        
    def get_aggr_list_name(self):
        return self.full_name + "_aggr_list"
        
    def get_type(self):
        return "t_" + self.full_name
        
    def get_type_and_name(self, aggrType):
        s = self.get_type() + " "
        if aggrType == 'owned':
            s += "* "
        s += self.d['name']
        return s
        
    def get_size(self):
        return "sizeof(" + self.get_type() + ")"
              
                    
class Aggregate:
    def __init__(self, d, id_gen, old_id, container_name):
        self.d = d
        self.full_name = container_name + "_" + self.d['item']['name']
        self.item = makeItem(self.d['item'], id_gen, old_id, self.full_name)
        
    def verify(self):
        "Check description in YAML file is valid and consistent."
        return self.item.verify()       
        
    def get_init(self, container_type_name, id_gen):
        "Return initialization string"
        s = self.item.get_init()
        s += "const cfg_mgr::Aggregate_data " + self.get_data_name() + " = {&"
        s += self.full_name + ", " + self.get_count_str()
        s += ", offsetof(" + container_type_name + ", " + self.item.d['name'] + ")};\n"
        s += self.get_instantiate()       
        return s
        
    def get_data_name(self):
        return self.full_name  + "_aggr_data"
        
    def get_count_str(self):
        "Return a string representing the count: either a symbolic constant's name, or just a string of an integer."
        try:
            count = self.d['count']['name']
        except:
            count = str(self.d['count'])
        return count
        
    def get_constant_definition(self):
        "Return string representing the symbolic constants used in the aggregate count"
        s = ""
        try:
            constant = self.d['count']
            s += "const " + constant['type'] + " " + constant['name'] + " = " + str(constant['value']) + ";\n"
        except:
            # If no counter that includes type, name and value, then there are no constants
            pass
        return s


class ContainedAggregate(Aggregate):
    def __init__(self, d, id_gen, old_id, container_name):
        Aggregate.__init__(self, d, id_gen, old_id, container_name)

    def get_instance_definition(self):
        s = self.item.get_type_and_name('contained')
        if self.d['count'] != 1:
            s += "[" + self.get_count_str() + "]"
        return s + ";\n"
                
    def get_instantiate(self):
        s = "const cfg_mgr::Contained_aggregate " + self.full_name + "_aggr(&" + self.get_data_name() + ");\n\n"
        return s
        
        
class OwnedAggregate(Aggregate):
    def __init__(self, d, id_gen, old_id, container_name):        
        Aggregate.__init__(self, d, id_gen, old_id, container_name)
        self.counter_name = ""
        if 'counter' in self.d:
            self.counter_name += container_name + "_" + self.d['counter']['item']['name']
            
    def verify(self):
        "Check description in YAML file is valid and consistent."
        self.verify_counter()
        self.item.verify()
        
    def verify_counter(self):
        "An owned aggregate that can contain more than one instance needs a counter"
        if not 'counter' in self.d:
            max_count = self.get_max_count()
            if max_count > 1:
                print "Warning: aggregate for", self.d['item']['name'], "has no counter, but max_count is", max_count
                return False
        return True  
        
    def get_instance_definition(self):
        return self.item.get_type_and_name('owned') + ";\n"
        
    def get_instantiate(self):
        s = "const cfg_mgr::Owned_aggregate " + self.full_name + "_aggr(&" + self.get_data_name()
        if len(self.counter_name) > 0:
            s += ", &" + self.counter_name + "_aggr"
        else:
            s += ", NULL"
        s += ");\n\n"
        return s
        
    def get_max_count(self):
        "Return numerical value for maximum number of instances of owned aggregate"
        try:
            # The value of the symbolic constant
            return self.d['count']['value']
        except:
            # Simple case: return the value
            return self.d['count']
        
        
def makeItem(d, container_id_gen, old_id, full_name):
    "Factory method returns an Item object of the requested class"
    if 'aggregate' in d: 
        return CompositeItem(d, container_id_gen, old_id, full_name)
    else:
        return SimpleItem(d, container_id_gen, old_id, full_name)
        

def makeAggregate(d, id_gen, old_id, container_name):
    "Factory method returns an Aggregate object of the requested class"
    if d['type'] == 'owned': 
        return OwnedAggregate(d, id_gen, old_id, container_name)
    else:
        return ContainedAggregate(d, id_gen, old_id, container_name)

        
def loadCfgData(cfgFileName):
    "Load configuration metadata from YAML config file"
    try:
        f = open(cfgFileName)
    except:
        print "Configuration file name not given."
        return
    print "Reading config file", cfgFileName
    data = f.read()
    f.close()
    return data


def loadIdData(baseFileName):
    "Read ID data file and return dictionary, or None if there's a problem with the input file"
    fname = baseFileName + "_id.yaml"
    try:
        f = open(fname)
    except IOError:
        print "Can't open ID file", fname
        return
    print "Reading ID file", fname
    data = f.read()
    f.close()
    return data

    
def makeBaseItem(yaml_cfg_text, id_text):
    "From the config file and the ID file, create objects to generate C++ code and a new ID file."
    try:
        cfg = yaml.load(yaml_cfg_text)
    except:
        print "config file can't be loaded as YAML"
        return
    try:
        base_item_config = cfg['item']
    except:
        print "Root element in configuration is not an item"
        return
    try:
        id_dict = yaml.load(id_text)
    except:
        # This happens in the normal case where no ID file exists yet
        print "ID file can't be loaded as YAML"
        return makeItem(base_item_config, Id_generator(None), None, base_item_config['name'])
    if id_dict['name'] != base_item_config['name']:
        # The ID data has no entry for the base item
        print "'{0}' in ID data file doesn't match '{1}' in config file: generating new IDs!".format(id_dict['name'], base_item_config['name'])
        id_dict = None
    return makeItem(base_item_config, Id_generator(None), id_dict, base_item_config['name'])


def saveIdData(baseFileName, old_id_text):
    "Save IDs to the ID file, including newly allocated ones and ones in the previous ID file."
    id_data = getIdData()
    # Compare the data, ignore the comments that are also part of the file text
    if old_id_text is not None:
        old_id_data = yaml.load(old_id_text)
        if id_data == old_id_data:
            # Don't overwrite file with same data, 'make' considers it a changed dependency
            return
    fname = baseFileName + "_id.yaml"
    f = open(fname, "w")
    f.write(getIdHeader(sys.argv[0]))
    f.write(yaml.dump(id_data, default_flow_style=False))
    f.close()
    
    
def getIdData():
    "Get current ID data, including newly allocated ones and ones in the previous ID file, in ID file format."
    # Special case: the top-level item is the only one that doesn't get its ID from a generator object
    id_dict = {}
    id_dict['name'] = baseItem.d['name']
    id_dict['id'] = int(baseItem.id)
    id_dict['components'] = baseItem.get_component_ids()
    return id_dict
    
    
def saveDefinitionFile(baseFileName, baseItem):
    "Make .h file containing type definitions"
    fdecl = open(baseFileName + ".h", "w")
    fdecl.write(getDeclHeader(sys.argv[0], sys.argv[1]))
    fdecl.write(baseItem.get_definition())
    fdecl.close()
    
    
def saveInititializationFile(baseFileName, baseItem):
    "Make .cpp file containing definitions and initializations"
    finit = open(baseFileName + ".cpp", "w")
    finit.write(getInitHeader(sys.argv[0], sys.argv[1]))
    finit.write("#include \"" + baseFileName + "_depend.h\"\n\n")
    finit.write("namespace {\n")
    finit.write(baseItem.get_init())
    finit.write("}\n\n")
    finit.write(baseItem.get_access_fn())
    finit.close()    
    
    
if __name__ == "__main__":
    baseFileName, extension = os.path.splitext(sys.argv[1])
    cfg_text = loadCfgData(sys.argv[1])
    if cfg_text is None:
        sys.exit()        
    id_text = loadIdData(baseFileName)
    baseItem = makeBaseItem(cfg_text, id_text)
    if baseItem is None:
        sys.exit()
    baseItem.verify()
    saveDefinitionFile(baseFileName, baseItem)
    saveInititializationFile(baseFileName, baseItem)
    saveIdData(baseFileName, id_text)
