""" C++ code generator
From YAML descriptor, generate .h file(s) containing user data structures
and the .cpp file that implements the initialization of the metadata
describing the contents of those structures.

Usage: python yaml_code_gen.py [source YAML file]


"""

import yaml
import sys
import time
import datetime

indent = "    "

def getCommonHdr(script, inputFile):
    return ("// Don't modify this file.  It was generated by " + script +
            "\n// from " + inputFile + " on " + str(datetime.date.today()) + ".\n")

def getDeclHeader(script, inputFile):
    return (getCommonHdr(script, inputFile) +
            """// It contains data structure definitions for configurable items managed by cfg_man.\n\n""")
    
def getInitHeader(script, inputFile):
    return (getCommonHdr(script, inputFile) +
            """// It contains initialization of metadata for configurable items managed by cfg_man.\n\n""")

    
class Id_generator():
    """Generate ID for TLV.  This is the simplest thing that could work, but not the best solution"""
    def __init__(self):
        self.id = 0
        
    def get_id(self):
        id_string = str(self.id)
        self.id += 1
        return id_string
    

class Item:
    def __init__(self, d):
        self.d = d
        
    def get_definition(self):
        """Definitions of structs definitions for composites"""
        return self.get_struct_definition()
        
    def get_metadata_name(self):
        return self.d['name'] + "_data"
        
    def get_common_metadata_init(self):
        s = indent + "{\n"
        s += 2 * indent + "\"" + self.d['name'] + "\",\n"
        s += 2 * indent + id_gen.get_id() + ",\n" # xxx fix this: IDs should be constant as possible within composites
        s += 2 * indent + self.get_size() + ",\n"
        s += 2 * indent
        if self.d['persistent']:
             s += "true\n"
        else:
            s += "false\n"
        s += indent + "},\n"
        return s
        
    
class SimpleItem(Item):
    def __init__(self, d):
        Item.__init__(self, d)
        self.is_string_type = False # By default, items aren't strings
        if "string" in d['type']:
            self.is_string_type = True
            self.string_len = d['type'].split()[1]
                   
    def verify(self):
        """Check item description in YAML file is valid and consistent."""
        return True
            
    def get_init(self):
        """Return string containing initialization of the metadata"""
        s = self.get_metadata_init()
        s += "const cm_simple_descriptor " + self.d['name'] + "(&" + self.get_metadata_name() + ");\n"
        return s
        
    def get_metadata_init(self):
        s = "const cm_simple_metadata " + self.get_metadata_name() + " = \n{\n"
        s += self.get_common_metadata_init()
        
        s += indent
        if 'set' in self.d:
            s += self.d['set']
        else:
            s += "NULL"
        s += ",\n"
        
        s += indent
        if 'setdef' in self.d:
            s += self.d['setdef']
        else:
            s += "NULL"
        s += ",\n"
        
        s += indent
        if 'print' in self.d:
            s += self.d['print']
        else:
            s += "NULL"
        s += ",\n"
        
        s += "};\n"
        return s
    
    def get_type_and_name(self, aggrType):
        """Get the type and the name, part of the definition line"""
        if self.is_string_type:
            s = "char "
        else:
            s = self.d['type'] + " "
        if aggrType == 'owned':
            s += "* "
        s += self.d['name']
        if self.is_string_type:
            s += "[" + self.string_len + "]"
        return s
        
    def get_size(self):
        s = "sizeof("
        if self.is_string_type:
            s += "char) * " + self.string_len
        else:
            s += self.d['type'] + ")"
        return s
        
    def get_definition(self):
        """No struct def for simple"""
        return ""
        
class CompositeItem(Item):
    def __init__(self, d):
        Item.__init__(self, d)

    def verify(self):
        """Check item description in YAML file is valid and consistent."""
        for a in self.d['aggregate']:
            makeAggregate(a).verify()
        return True
            
    def get_definition(self):
        """Return string representing struct definition, including pre-pended definitions of referenced structs"""
        s = ""
        for a in self.d['aggregate']:
            s += makeAggregate(a).get_constant_definition()
            s += makeItem(a['item']).get_definition()
        s += "\nstruct " + self.get_type() + "\n{\n"
        for a in self.d['aggregate']:
            s += indent + makeAggregate(a).get_instance_definition()
        s += "};\n"
        return s
        
    def get_init(self):
        """Return string containing initialization of the metadata, including pre-pended initialization of included data"""
        s = ""
        for a in self.d['aggregate']:
            s += makeAggregate(a).get_init(self.get_type()) 
        s += self.get_aggr_list_init()
        s += self.get_metadata_init()
        s += "const cm_composite_descriptor " + self.d['name'] + "(&" + self.get_metadata_name() + ");\n"
        return s
        
    def get_aggr_list_init(self):
        s = "const cm_aggregate * const " + self.get_aggr_list_name() + "[] = \n{\n"
        for a in self.d['aggregate']:
            s += indent + "&" + a['item']['name'] + "_aggr,\n"
        s += "\n};\n"
        return s
        
    def get_metadata_init(self):
        s = "const cm_composite_metadata " + self.get_metadata_name() + " = \n{\n"
        s += self.get_common_metadata_init()
        s += indent + self.get_aggr_list_name() + ",\n"
        s += indent + "sizeof(" + self.get_aggr_list_name() + ")/sizeof(" + self.get_aggr_list_name() + "[0])\n"
        s += "};\n"
        return s
        
    def get_aggr_list_name(self):
        return self.d['name'] + "_aggr_list"
        
    def get_type(self):
        return "t_" + self.d['name']
        
    def get_type_and_name(self, aggrType):
        s = self.get_type() + " "
        if aggrType == 'owned':
            s += "* "
        s += self.d['name']
        return s
        
    def get_size(self):
        return "sizeof(" + self.get_type() + ")"
              
                    
class Aggregate:
    def __init__(self, d):
        self.d = d
        
    def verify(self):
        """Check description in YAML file is valid and consistent."""
        return makeItem(self.d['item']).verify()       
        
    def get_init(self, container_type_name):
        """Return initialization string"""
        item = makeItem(self.d['item'])
        s = item.get_init()
        s += "const cm_aggregate_data " + self.get_data_name() + " = {&"
        s += item.d['name'] + ", " + self.get_count_str()
        s += ", offsetof(" + container_type_name + ", " + item.d['name'] + ")};\n"
        s += self.get_instantiate()
        
        return s
        
    def get_data_name(self):
        return self.d['item']['name'] + "_aggr_data"
        
    def get_count_str(self):
        """Return a string representing the count: either the name of a symbolic constant, or just a string of an integer."""
        try:
            count = self.d['count']['name']
        except:
            count = str(self.d['count'])
        return count
        
    def get_constant_definition(self):
        s = ""
        try:
            constant = self.d['count']
            s += "const " + constant['type'] + " " + constant['name'] + " = " + str(constant['value']) + ";\n"
        except:
            """If no counter that includes type, name and value, then there are no constants"""
            pass
        return s
        
class ContainedAggregate(Aggregate):
    def __init__(self, d):
        Aggregate.__init__(self, d)
        
    def get_instance_definition(self):
        s = makeItem(self.d['item']).get_type_and_name('contained')
        if self.d['count'] != 1:
            s += "[" + self.get_count_str() + "]"
        return s + ";\n"
        
    def get_type(self):
        return "cm_contained_aggregate"
        
    def get_instantiate(self):
        item = makeItem(self.d['item']) 
        s = "const " + self.get_type() + " " + item.d['name'] + "_aggr(&" + self.get_data_name() + ");\n\n"
        return s
        
        
class OwnedAggregate(Aggregate):
    def __init__(self, d):        
        Aggregate.__init__(self, d)
        
    def verify(self):
        """Check description in YAML file is valid and consistent."""
        self.verify_counter()
        makeItem(self.d).verify()
        
    def verify_counter(self):
        """An owned aggregate that can contain more than one instance needs a counter"""
        if not 'counter' in self.d:
            max_count = self.get_max_count()
            if max_count > 1:
                print "Warning: aggregate for", self.d['item']['name'], "has no counter, but max_count is", max_count
                return False
        return True  
        
    def get_instance_definition(self):
        item = makeItem(self.d['item'])
        return item.get_type_and_name('owned') + ";\n"
        
    def get_type(self):
        return "cm_owned_aggregate"
        
    def get_instantiate(self):
        item = makeItem(self.d['item'])
        s = "const " + self.get_type() + " " + item.d['name'] + "_aggr(&" + self.get_data_name()
        if 'counter' in self.d:
            s += ", &" + self.d['counter']['item']['name'] + "_aggr"
        else:
            s += ", NULL"
        s += ");\n\n"
        return s
        
    def get_max_count(self):
        """Return numerical value for maximum number of instances of owned aggregate"""
        try:
            # The value of the symbolic constant
            return self.d['count']['value']
        except:
            # Simple case: return the value
            return self.d['count']
        
        
def makeItem(d):
    """Factory method returns an Item object of the requested class"""
    if 'aggregate' in d: 
        return CompositeItem(d)
    else:
        return SimpleItem(d)
        

def makeAggregate(d):
    """Factory method returns an Aggregate object of the requested class"""
    if d['type'] == 'owned': 
        return OwnedAggregate(d)
    else:
        return ContainedAggregate(d)      
        

f = open(sys.argv[1])
print "Reading", sys.argv[1]
data = yaml.load(f)
#print "============================================="
#print data
#print "============================================="

f.close()

try:
    i = data['item']
except:
    print "Root element in", sys.argv[1], "is not an item: exit"
    sys.exit()
    
id_gen = Id_generator()
baseItem = makeItem(i)
baseItem.verify()
finit = open("cfg.cpp", "w")
fdecl = open("cfg.h", "w")
fdecl.write(getDeclHeader(sys.argv[0], sys.argv[1]))
finit.write(getInitHeader(sys.argv[0], sys.argv[1]))
fdecl.write(baseItem.get_definition())
finit.write(baseItem.get_init())
finit.close()
fdecl.close()
